//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeBuilderEntities : DbContext
    {
        public ResumeBuilderEntities()
            : base("name=ResumeBuilderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EDUCATION> EDUCATIONs { get; set; }
        public virtual DbSet<SKILL> SKILLS { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<WORKEXPERIENCE> WORKEXPERIENCEs { get; set; }
    }
}
