//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKEXPERIENCE
    {
        public int ID { get; set; }
        public string JOB_TITLE { get; set; }
        public string EMPLOYER { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> START_MONTH { get; set; }
        public Nullable<System.DateTime> START_YEAR { get; set; }
        public Nullable<System.DateTime> END_MONTH { get; set; }
        public string END_YEAR { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ID_PERSON { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
